#!/bin/env python3
import sys
import os

LOCATION = "/opt/wsdect"

def _help():
    print("\n[+] Get update")
    print("    ./wsdect update")
    print("\n[+] Scan webshell")
    print("    ./wsdect scan <PATH>\n")

def _update():
    os.system("cd %s; git pull; cd -" % LOCATION)

def _scan(PATH):
    os.system("yara -r %s/rules/* %s 2>/dev/null" % (LOCATION, PATH))

def main():
    print("\n[+] wsdect 1.0")
    if len(sys.argv) < 2:
        print("[-] Error: arguments not found")
        _help()
        return -1
    elif sys.argv[1] == "update":
        try:
            fp = open("/etc/shadow", "rt")
            fp.close()
        except:
            print("This command requires root privileges.")
            return -1
        _update()
        return 0
    elif sys.argv[1] == "scan":
        if len(sys.argv) < 3:
            print("[-] Error: arguments not found")
            _help()
            return -1
        else:
            _scan(sys.argv[2])
            return 0
    else:
        print("[-] Error: arguments isn't valid")
        _help()
        return -1

if __name__ == "__main__":
    exit(main())
